Controllers/ConsultantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CeeLearnAndDo.Data;
using CeeLearnAndDo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CeeLearnAndDo.Controllers
{
    public class ConsultantsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _iweb;

        public ConsultantsController(ApplicationDbContext context, IWebHostEnvironment iweb)
        {
            _context = context;
            _iweb = iweb;
        }

        public IActionResult Index()
        {
            var consultant = _context.Consultant;
            List<Consultant> consultants = new List<Consultant>();

            foreach (Consultant consult in consultants)
            {
                Consultant cst = new Consultant
                {
                    ConsultantId = consult.ConsultantId,
                    Naam = consult.Specialiteiten,
                    Email = consult.Email,
                    Omschrijving = consult.Omschrijving,
                    Profielfoto = consult.Profielfoto
                };
                consultants.Add(cst);
            }

            return View(consultant);
        }

        // GET: Admin/Artikelen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consultant = await _context.Consultant
                .FirstOrDefaultAsync(m => m.ConsultantId == id);
            if (consultant == null)
            {
                return NotFound();
            }

            return View(consultant);
        }

    }

}

Controllers/ContactInzendingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CeeLearnAndDo.Data;
using CeeLearnAndDo.Models;

namespace CeeLearnAndDo.Controllers
{
    public class ContactInzendingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactInzendingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ContactInzendings
        public async Task<IActionResult> Index()
        {
            return View(await _context.ContactInzending.ToListAsync());
        }

        // GET: ContactInzendings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactInzending = await _context.ContactInzending
                .FirstOrDefaultAsync(m => m.InzendingId == id);
            if (contactInzending == null)
            {
                return NotFound();
            }

            return View(contactInzending);
        }

        // GET: ContactInzendings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ContactInzendings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InzendingId,Naam,Telefoon,Email,Datum,Content")] ContactInzending contactInzending)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contactInzending);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Message = "Succesvol verzonden!";
            return View(contactInzending);
        }

        // GET: ContactInzendings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactInzending = await _context.ContactInzending.FindAsync(id);
            if (contactInzending == null)
            {
                return NotFound();
            }
            return View(contactInzending);
        }

        // POST: ContactInzendings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InzendingId,Naam,Telefoon,Email,Datum,Content")] ContactInzending contactInzending)
        {
            if (id != contactInzending.InzendingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contactInzending);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactInzendingExists(contactInzending.InzendingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contactInzending);
        }

        // GET: ContactInzendings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactInzending = await _context.ContactInzending
                .FirstOrDefaultAsync(m => m.InzendingId == id);
            if (contactInzending == null)
            {
                return NotFound();
            }

            return View(contactInzending);
        }

        // POST: ContactInzendings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contactInzending = await _context.ContactInzending.FindAsync(id);
            _context.ContactInzending.Remove(contactInzending);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactInzendingExists(int id)
        {
            return _context.ContactInzending.Any(e => e.InzendingId == id);
        }
    }
}

Controllers/VragenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CeeLearnAndDo.Data;
using CeeLearnAndDo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CeeLearnAndDo.Controllers
{
    public class VragenController : Controller
    {
        private readonly ApplicationDbContext _context;
        public VragenController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var vragen = _context.Vraag;
            List<Vraag> vraags = new List<Vraag>();

            foreach (Vraag vraag in vraags)
            {
                Vraag vrg = new Vraag
                {
                    VraagId = vraag.VraagId,
                    Titel = vraag.Titel,
                    DatumAangemaakt = vraag.DatumAangemaakt
                };
                vraags.Add(vrg);
            }

            return View(vragen);
        }

        

        [Authorize]
        [HttpGet]
        [Area("Admin")]
        public IActionResult Details(int id)
        {
            var Vraag  = _context.Vraag.Find(id);
            var Reactie = _context.Vraag.Include(v => v.Reacties_Vraag).FirstOrDefault(v => v.VraagId == id);
            return View(Vraag);
        }

        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CeeLearnAndDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("css", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img width="50%" src="~/img/logotransparant.png"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultants" asp-action="Index">Consultants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vragen" asp-action="Index">Veelgestelde vragen</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Kennisbank" asp-controller="" asp-action="Index">Kennisbank</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContactInzendings" asp-action="Create">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CeeLearnAndDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>