Controllers/ArtikelenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CeeLearnAndDo.Data;
using CeeLearnAndDo.Models;
using Microsoft.AspNetCore.Authorization;

namespace CeeLearnAndDo.Areas.Admin.Controllers
{

    public class ArtikelenController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ArtikelenController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Artikelen
        public IActionResult Index()
        {
            var artikelen = _context.Artikel;
            List<Artikel> artikels = new List<Artikel>();

            foreach (Artikel artikel in artikels)
            {
                Artikel artl = new Artikel
                {
                    ArtikelId = artikel.ArtikelId,
                    Titel = artikel.Titel,
                    Datum = artikel.Datum
                };
                artikels.Add(artl);
            }

            return View(artikelen);
        }

        // GET: Admin/Artikelen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artikel = await _context.Artikel
                .FirstOrDefaultAsync(m => m.ArtikelId == id);
            if (artikel == null)
            {
                return NotFound();
            }

            return View(artikel);
        }

        // GET: Admin/Artikelen/Create
        public IActionResult NieuwArtikel()
        {
            return View();
        }

        // POST: Admin/Artikelen/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NieuwArtikel([Bind("ArtikelId,Titel,Categorie,Content,Datum,Publicatie,OmslagAfbeelding")] Artikel artikel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artikel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(artikel);
        }

        // GET: Admin/Artikelen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artikel = await _context.Artikel.FindAsync(id);
            if (artikel == null)
            {
                return NotFound();
            }
            
            return View(artikel);
        }

        // POST: Admin/Artikelen/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ArtikelId,Titel,Categorie,Content,Datum,Publicatie,OmslagAfbeelding")] Artikel artikel)
        {
            if (id != artikel.ArtikelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(artikel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtikelExists(artikel.ArtikelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(artikel);
        }

        // GET: Admin/Artikelen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artikel = await _context.Artikel

                .FirstOrDefaultAsync(m => m.ArtikelId == id);
            if (artikel == null)
            {
                return NotFound();
            }

            return View(artikel);
        }

        // POST: Admin/Artikelen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artikel = await _context.Artikel.FindAsync(id);
            _context.Artikel.Remove(artikel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtikelExists(int id)
        {
            return _context.Artikel.Any(e => e.ArtikelId == id);
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CeeLearnAndDo.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CeeLearnAndDo.Controllers
{ }
/*{
    public class ContactController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Authorize]
        public ActionResult Index()
        {
            var contactInzending = _context.ContactInzending;
            List<ContactInzending> contactInzendings = new List<ContactInzending>();
            
            foreach (ContactInzending contactinzending in contactInzendings)
            {
                ContactInzending cnt = new ContactInzending
                {
                   Console.WriteLine("test");
                }
            }

            return View(model: contactInzending);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <ActionResult> Create(Models.ContactInzending model)
        {
            if(ModelState.IsValid)
            {
                _context.ContactInzending.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
} */

Controllers/ContactInzendingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CeeLearnAndDo.Data;
using CeeLearnAndDo.Models;

namespace CeeLearnAndDo.Controllers
{
    public class ContactInzendingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactInzendingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ContactInzendings
        public async Task<IActionResult> Index()
        {
            return View(await _context.ContactInzending.ToListAsync());
        }

        // GET: ContactInzendings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactInzending = await _context.ContactInzending
                .FirstOrDefaultAsync(m => m.InzendingId == id);
            if (contactInzending == null)
            {
                return NotFound();
            }

            return View(contactInzending);
        }

        // GET: ContactInzendings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ContactInzendings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InzendingId,Naam,Telefoon,Email,Datum,Content")] ContactInzending contactInzending)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contactInzending);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Message = "Succesvol verzonden!";
            return View(contactInzending);
        }

        // GET: ContactInzendings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactInzending = await _context.ContactInzending.FindAsync(id);
            if (contactInzending == null)
            {
                return NotFound();
            }
            return View(contactInzending);
        }

        // POST: ContactInzendings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InzendingId,Naam,Telefoon,Email,Datum,Content")] ContactInzending contactInzending)
        {
            if (id != contactInzending.InzendingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contactInzending);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactInzendingExists(contactInzending.InzendingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contactInzending);
        }

        // GET: ContactInzendings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactInzending = await _context.ContactInzending
                .FirstOrDefaultAsync(m => m.InzendingId == id);
            if (contactInzending == null)
            {
                return NotFound();
            }

            return View(contactInzending);
        }

        // POST: ContactInzendings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contactInzending = await _context.ContactInzending.FindAsync(id);
            _context.ContactInzending.Remove(contactInzending);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactInzendingExists(int id)
        {
            return _context.ContactInzending.Any(e => e.InzendingId == id);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CeeLearnAndDo.Models;

namespace CeeLearnAndDo.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		public IActionResult Contact()
		{
			return View();
		}

		public IActionResult Consultants()
		{
			return View();
		}

		public IActionResult Vraag_en_Antwoord()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/VragenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CeeLearnAndDo.Data;
using CeeLearnAndDo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CeeLearnAndDo.Controllers
{
    public class VragenController : Controller
    {
        private readonly ApplicationDbContext _context;
        public VragenController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var vragen = _context.Vraag;
            List<Vraag> vraags = new List<Vraag>();

            foreach (Vraag vraag in vraags)
            {
                Vraag vrg = new Vraag
                {
                    VraagId = vraag.VraagId,
                    Titel = vraag.Titel,
                    DatumAangemaakt = vraag.DatumAangemaakt
                };
                vraags.Add(vrg);
            }

            return View(vragen);
        }

        

        [Authorize]
        [HttpGet]
        [Area("Admin")]
        public IActionResult Details(int id)
        {
            var Vraag  = _context.Vraag.Find(id);
            var Reactie = _context.Vraag.Include(v => v.Reacties_Vraag).FirstOrDefault(v => v.VraagId == id);
            return View(Vraag);
        }

        
    }
}

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="container">
        <div align="center">
            <h1>Contact</h1>
        </div>
    </div>

<div class="container">
    <div class="row">
        <div class="col-sm">
            Heeft u een opmerking of een vraag? Neem contact met ons op door het formulier in te vullen.<br />

        </div>
        <div class="col-md">
            <form action="\Views\Home\BedanktPagina.cshtml\>
                <label for="fname">Naam:</label><br>
                <input type="text" id="fname" name="fname" value="John Doe"><br>
                <label for="fname">Telefoon:</label><br>
                <input type="tel" id="Telefoon" name="Telefoon" value="06 28916944"><br>
                <label for="email">Email-adres:</label><br>
                <input type="Email" id="Email" name="Email" value="JohnDoe@gmail.com"><br>
                <label for="message">Bericht</label><br>
                <input type="text" id="Content" name="Content" value=" "><br><br>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/img/slide1.png" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Wij beantwoorden uw vragen over IT oplossingen</h5>
                    <p>Onze consultants staan voor u klaar</p>
                </div>
            </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/img/slide2.jpg" alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Goedwerkende IT oplossingen</h5>
                        <p>Die er voor zorgen dat uw data snel, veilig en makkelijk te bereiken is</p>
                    </div>
                </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/img/slide3.jpg" alt="Third slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Kies voor CeeLearnAndo</h5>
                            <p>Dan kunt u zorgeloos doen waar u goed in bent</p>
                        </div>
                    </div>
                    </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
<br /><br />
    <div class="row">
        <div class="col-sm-4">
            <div class="card text-white bg-primary">
                <div class="card-body">
                    <h5 class="card-title">Onze artikelen</h5>
                    <p class="card-text">Leer van de CeeLearnAndDo consultants, we schrijven dagelijks nieuwe artikelen.</p>
                    <a asp-area="" asp-controller="Artikelen" asp-action="Index" class="btn btn-primary">Bekijk artikelen</a>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card text-white bg-info">
                <div class="card-body">
                    <h5 class="card-title">Alles wat u wilt weten</h5>
                    <p class="card-text">Op onze FAQ pagina publiceren we vragen en antwoorden.</p>
                    <a asp-area="" asp-controller="Vragen" asp-action="Index" class="btn btn-primary">Veel gestelde vragen</a>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card text-white bg-secondary">
                <div class="card-body">
                    <h5 class="card-title">Iets anders vragen?</h5>
                    <p class="card-text">Via het contactformulier kunt u ons benaderen of klant worden.</p>
                    <a asp-area="" asp-controller="ContactInzendings" asp-action="Create" class="btn btn-primary">Contact opnemen</a>
                </div>
            </div>
        </div>
    </div>

Views/Home/Veelgesteldevragen.cshtml
@model IEnumerable<CeeLearnAndDo.Models.Vraag>

@{
    ViewData["Title"] = "Veelgesteldevragen";
    Layout = "~/Areas/Admin/Views/Shared/blank.cshtml";
}

<h1>Veelgesteldevragen</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumAangemaakt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumBijgewerkt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Toestemming)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumAangemaakt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumBijgewerkt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Toestemming)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.VraagId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.VraagId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.VraagId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>